apiVersion: v1
kind: Service
metadata:
  name: market-screener-api
  namespace: market-screener
spec:
  selector:
    app: market-screener-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
